// Package telemetry provides privacy-first observability for CLIs generated by CLICreator.
//
// Each command invocation emits an Event to the CLICreator platform, giving API owners
// visibility into how their CLI is being used — by AI agents, CI pipelines, or humans —
// without ever capturing flag values, credentials, or PII.
//
// Privacy guarantees:
//   - FlagsUsed contains only flag NAMES, never values (no credentials, no PII).
//   - BaseURLHash is a SHA-256 prefix — identifies the environment without exposing the URL.
//   - Users opt out by setting <PREFIX>_NO_TELEMETRY=1.
//   - Telemetry is disabled by default when no token is embedded at generation time.
package telemetry

import (
	"os"
	"time"
)

// CallerType identifies what kind of process is running the CLI.
type CallerType string

const (
	CallerHuman CallerType = "human" // interactive terminal session
	CallerAgent CallerType = "agent" // AI coding agent (Claude Code, Cursor, Cline, etc.)
	CallerCI    CallerType = "ci"    // CI/CD pipeline
)

// CallerInfo holds the detected identity of the CLI caller.
// All fields are derived from environment variables — no heuristics beyond env inspection.
type CallerInfo struct {
	Type      CallerType // "human", "agent", or "ci"
	AgentType string     // e.g. "claude_code", "cursor", "cline"; empty for non-agents
	SessionID string     // agent session ID from env var, if available; empty otherwise
}

// agentProbe describes one env-var heuristic for detecting an agent caller.
type agentProbe struct {
	env        string // env var whose non-empty value signals this agent is running
	agentType  string // canonical agent type string used in telemetry events
	sessionEnv string // env var holding the session ID (may equal env, or be empty)
}

// agentProbes is evaluated in order; first match wins.
// Ordered roughly by specificity — env vars unique to one agent come first.
var agentProbes = []agentProbe{
	{"CLAUDE_CODE", "claude_code", "CLAUDE_CODE_SESSION_ID"},
	{"CURSOR_SESSION_ID", "cursor", "CURSOR_SESSION_ID"},
	{"CLINE_SESSION_ID", "cline", "CLINE_SESSION_ID"},
	{"WINDSURF_SESSION", "windsurf", "WINDSURF_SESSION"},
	{"GITHUB_COPILOT", "github_copilot", ""},
	{"AMAZON_Q_SESSION", "amazon_q", "AMAZON_Q_SESSION"},
	{"CODEX", "codex", ""},
	{"AIDER", "aider", ""},
	{"CODY", "cody", ""},
	{"GEMINI_CODE_ASSIST", "gemini", ""},
}

// DetectCaller inspects environment variables to identify who is running the CLI.
// It is heuristic and best-effort; it never blocks or makes network calls.
// When in doubt it returns CallerHuman — false negatives are safe, false positives are not.
func DetectCaller() CallerInfo {
	for _, p := range agentProbes {
		if os.Getenv(p.env) != "" {
			sessionID := ""
			if p.sessionEnv != "" {
				sessionID = os.Getenv(p.sessionEnv)
			}
			return CallerInfo{
				Type:      CallerAgent,
				AgentType: p.agentType,
				SessionID: sessionID,
			}
		}
	}

	if os.Getenv("CI") != "" ||
		os.Getenv("GITHUB_ACTIONS") != "" ||
		os.Getenv("GITLAB_CI") != "" ||
		os.Getenv("CIRCLECI") != "" ||
		os.Getenv("BUILDKITE") != "" ||
		os.Getenv("JENKINS_URL") != "" {
		return CallerInfo{
			Type:      CallerCI,
			SessionID: os.Getenv("GITHUB_RUN_ID"), // empty for non-GHA CI
		}
	}

	return CallerInfo{Type: CallerHuman}
}

// Event represents one CLI command invocation. Sent asynchronously to the CLICreator
// platform after the command completes, giving API owners a real-time window into how
// their generated CLI is being used.
//
// Sizing: ~500 bytes JSON — designed for batching at low egress cost.
type Event struct {
	// Identity — baked in at CLI generation time by the generator.
	CLIID      string `json:"cli_id"`      // CLICreator platform token
	CLIName    string `json:"cli_name"`    // e.g. "ticketmaster"
	CLIVersion string `json:"cli_version"` // e.g. "1.0.0"

	// Command — what was invoked.
	// Full Cobra command path, e.g. "ticketmaster discovery events search".
	Command string `json:"command"`

	// Caller — who invoked it and from what context.
	CallerType string `json:"caller_type"`          // "human", "agent", or "ci"
	AgentType  string `json:"agent_type,omitempty"` // "claude_code", "cursor", "cline", etc.
	SessionID  string `json:"session_id,omitempty"` // agent session ID when available

	// Timing.
	Timestamp  time.Time `json:"timestamp"`
	DurationMS int64     `json:"duration_ms"`

	// Invocation style — HOW the command was called.
	// IMPORTANT: FlagsUsed contains flag NAMES only. Values are intentionally absent.
	FlagsUsed    []string `json:"flags_used"`
	OutputFormat string   `json:"output_format,omitempty"` // "compact", "json", "table", etc.
	UsedJQ       bool     `json:"used_jq,omitempty"`       // --jq was passed
	UsedSchema   bool     `json:"used_schema,omitempty"`   // --schema was passed
	UsedDryRun   bool     `json:"used_dry_run,omitempty"`  // --dry-run was passed

	// Result.
	ExitCode   int    `json:"exit_code"`
	ErrorCode  string `json:"error_code,omitempty"`  // e.g. "auth_failed", "network_error"
	HTTPStatus int    `json:"http_status,omitempty"` // upstream HTTP status; 0 for non-HTTP errors

	// Environment — privacy-preserving identification of the deployment target.
	// First 16 hex chars of SHA-256(base URL). Distinguishes prod vs staging
	// without storing the URL itself.
	BaseURLHash string `json:"base_url_hash,omitempty"`
}
